
<div class="row">
   <!--  <div class="col-md-4  toolbar-box">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title" style="font-size: 14px">Tool box</h3>
            </div>
            <div class="panel-body">
                <button class="btn btn-danger open-view-user-modal tool-button" onclick="updateMultiStatus(1)">
                    <span class="btn-toolbutton">D</span>
                </button> 
                <button  class="btn btn-success open-edit-user-modal tool-button"  onclick="updateMultiStatus(0)">
                    <span class="btn-toolbutton">E</span>
                </button>
                <button class="btn btn-danger open-delete-user-modal tool-button" onclick="multiDetele()">
                    <span class="glyphicon glyphicon-trash">
                    </span>
                </button>
            </div>
        </div>
    </div> -->
    <div class="col-lg-12">
        <div class="card">
            <h1><?=$news->getTitle()?></h1>
            <?=$news->getContent()?>
        </div>
    </div>
</div>

</div>