<?php if ($this->pageCount): ?>
<div class="col-lg-12 m-b-30">
  <nav>
    <ul class="pagination">

    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
        <li class="page-item">
          <a class="page-link" href="<?= $this->url($this->route, [], ['query'=>['page'=>$this->previous,'ip'=>$this->data['ip']]]); ?>" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>  
    <?php else: ?>
        <li class="page-item">
            <span class="page-link" aria-hidden="true">&laquo;</span>      
        </li>  
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <li class="page-item">
            <a class="page-link" href="<?= $this->url($this->route, [], ['query'=>['page'=>$page,'ip'=>$this->data['ip']]]); ?>"><?= $this->escapeHtml($page); ?></a>
        </li>    
      <?php else: ?>
        <li class="page-item">
            <span  class="page-link" aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span> 
        </li>    
      <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
        <li class="page-item">
          <a class="page-link" href="<?php echo $this->url($this->route, [], ['query'=>['page'=>$this->next,'ip'=>$this->data['ip']]]); ?>" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>  
    <?php else: ?>
        <li class="page-item">
            <span class="page-link" aria-hidden="true">&raquo;</span>      
        </li> 
    <?php endif; ?>
    </ul>
  </nav>
</div>
<?php endif; ?>