<?php
require "Classes/PHPExcel.php";
?>
<div class="row">

    <div class="col-lg-12">
        <div class="card">
            <div class="card-body ">

        <h4 class="card-title">Phân tích cổ phiếu  <?=$stock->getName()?></h4>
                
<div class="container">

  <ul class="nav nav-tabs">
    <li class="active"><a class="tabbutton btn btn-primary" data-toggle="tab" href="#home">Biểu đồ</a></li>
    <li><a data-toggle="tab" class="tabbutton btn btn-success" href="#menu1">Lịch sử</a></li>
    <li><a data-toggle="tab" class="tabbutton btn btn-warning" href="#menu2">Báo cáo</a></li>
  <li><a data-toggle="tab" class="tabbutton btn btn-primary" href="#menu3">Phân tích tin đồn</a></li>
  <li><a data-toggle="tab" class="tabbutton btn btn-danger" href="#menu4">Dự báo</a></li>
  </ul>
  <br><br>
  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
        <img src="/img/graph/<?=$id?>.png">
        <br>
        <ul>
            <li>Nhìn chung đồ thị chứng khoán ngân hàng vietcombank có xu hưóng tăng, tuy có giảm trong thưòi gian gần đây nhưng có thể sẽ tăng thêm trong tưong lai</li>
            <li>Đường EMA là minh chứng cho cu hướng tăng của đồ thị trong tưiuong lai</li>
        </ul>
         <?=$analysis->getGraphHtml()?>
      </div>
    <div id="menu1" class="tab-pane fade">
      <div class="table-responsive">
                    <?php
                // Đường dẫn file
                $file = 'data/excel/'.$id.'.xlsx';

                // $file = 'data/excel/data.xlsx';
                //Tiến hành xác thực file
                $objFile = PHPExcel_IOFactory::identify($file);
                $objData = PHPExcel_IOFactory::createReader($objFile);

                //Chỉ đọc dữ liệu
                $objData->setReadDataOnly(true);

                // Load dữ liệu sang dạng đối tượng
                $objPHPExcel = $objData->load($file);

                //Lấy ra số trang sử dụng phương thức getSheetCount();
                // Lấy Ra tên trang sử dụng getSheetNames();

                //Chọn trang cần truy xuất
                $sheet = $objPHPExcel->setActiveSheetIndex(0);

                //Lấy ra số dòng cuối cùng
                $Totalrow = $sheet->getHighestRow();
                //Lấy ra tên cột cuối cùng
                $LastColumn = $sheet->getHighestColumn();

                //Chuyển đổi tên cột đó về vị trí thứ, VD: C là 3,D là 4
                $TotalCol = PHPExcel_Cell::columnIndexFromString($LastColumn);

                //Tạo mảng chứa dữ liệu
                $data = [];

                //Tiến hành lặp qua từng ô dữ liệu
                //----Lặp dòng, Vì dòng đầu là tiêu đề cột nên chúng ta sẽ lặp giá trị từ dòng 2
                for ($i = 2; $i <= $Totalrow; $i++) {
                    //----Lặp cột
                    for ($j = 0; $j < $TotalCol; $j++) {
                        // Tiến hành lấy giá trị của từng ô đổ vào mảng
                        $data[$i - 2][$j] = $sheet->getCellByColumnAndRow($j, $i)->getValue();;
                    }
                }
                //Hiển thị mảng dữ liệu
                echo '<pre>';
                // print_r($data[0]);
                // Date  Close   Volume  Open    High    Low
                // <DTYYYYMMDD>    <Open>  <High>  <Low>   <Close> <Volume>


                    ?>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Open</th>
                                <th>High</th>
                                <th>Low</th>
                                <th>Close</th>
                                <th>Volume</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php 
                            foreach ($data as $row) {
                        ?>
                        <tr>
                                    <td><?=$row[2]?></td>
                                    <td><?=$row[3]?></td>
                                    <td><?=$row[4]?></td>
                                    <td><?=$row[5]?></td>
                                    <td><?=$row[6]?></td>
                                    <td><?=$row[7]?></td>

                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
    </div>
    <div id="menu2" class="tab-pane fade">
        <br>
         <?=$analysis->getReportHtml()?>
      <img src="">
    </div>
     <div id="menu3" class="tab-pane fade">
        <img src="/img/news/<?=$id?>.png">     
           <br>
           Dựa vào biểu đồ tin đồn, có thể thấy số lượng tin đồn tiêu cực giảm dần sau thời gian gần đây, biểu hiện cho xu hưóng tăng của cổ phiếu trong thời gian tiếp theo
         <?=$analysis->getNewsHtml()?>
      </div>
   
      <div id="menu4" class="tab-pane fade">
        <img src="/img/predict.png">     
           <br>
      </div>
  </div>
</div>
                
            </div>
          
        </div>
    </div>
</div>

</div>