<?php
$this->headTitle('profile');

// $this->mainMenu()->setActiveItemId('profile');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Settings'=>$this->url('application', ['action'=>'profile']),
    ]);
    ?>

    <h2>Thông tin cá nhân</h2>

    <div class="row">
        
        <div class="col-md-4">
           <img style="width: 200px;height: 200px" src="<?=$user->getAvatar()?>" onError="this.onerror=null;this.src='/img/1.jpg';">

       </div>
       <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
            </tr>
            <tr>
                <th>Họ tên:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></td>
            </tr>
            <tr>
                <tr>
                    <th>Vài trò</th>
                    <td><?= $this->escapeHtml($user->getRoleAsString()) ?></td>
                </tr>
            </table>
        </div>
    </div>
